/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding/workspace'
import { Route as OnboardingInviteRouteImport } from './routes/onboarding/invite'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as WSlugIndexRouteImport } from './routes/w/$slug/index'
import { Route as WSlugNotificationsRouteImport } from './routes/w/$slug/notifications'
import { Route as WSlugApprovalsRouteImport } from './routes/w/$slug/approvals'
import { Route as WSlugWorkflowsIndexRouteImport } from './routes/w/$slug/workflows/index'
import { Route as WSlugSettingsIndexRouteImport } from './routes/w/$slug/settings/index'
import { Route as WSlugExecutionsIndexRouteImport } from './routes/w/$slug/executions/index'
import { Route as WSlugWorkflowsWorkflowIdRouteImport } from './routes/w/$slug/workflows/$workflowId'
import { Route as WSlugSettingsSecretsRouteImport } from './routes/w/$slug/settings/secrets'
import { Route as WSlugSettingsMembersRouteImport } from './routes/w/$slug/settings/members'
import { Route as WSlugExecutionsExecutionIdRouteImport } from './routes/w/$slug/executions/$executionId'
import { Route as WSlugWorkflowsWorkflowIdIndexRouteImport } from './routes/w/$slug/workflows/$workflowId/index'
import { Route as WSlugWorkflowsWorkflowIdBuilderRouteImport } from './routes/w/$slug/workflows/$workflowId/builder'
import { Route as WSlugWorkflowsWorkflowIdExecutionsExecutionIdRouteImport } from './routes/w/$slug/workflows/$workflowId/executions/$executionId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/onboarding/workspace',
  path: '/onboarding/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/onboarding/invite',
  path: '/onboarding/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugNotificationsRoute = WSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugApprovalsRoute = WSlugApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugWorkflowsIndexRoute = WSlugWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsIndexRoute = WSlugSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugExecutionsIndexRoute = WSlugExecutionsIndexRouteImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugWorkflowsWorkflowIdRoute =
  WSlugWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => WSlugRoute,
  } as any)
const WSlugSettingsSecretsRoute = WSlugSettingsSecretsRouteImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsMembersRoute = WSlugSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugExecutionsExecutionIdRoute =
  WSlugExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => WSlugRoute,
  } as any)
const WSlugWorkflowsWorkflowIdIndexRoute =
  WSlugWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WSlugWorkflowsWorkflowIdRoute,
  } as any)
const WSlugWorkflowsWorkflowIdBuilderRoute =
  WSlugWorkflowsWorkflowIdBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => WSlugWorkflowsWorkflowIdRoute,
  } as any)
const WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute =
  WSlugWorkflowsWorkflowIdExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => WSlugWorkflowsWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/approvals': typeof WSlugApprovalsRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/executions/$executionId': typeof WSlugExecutionsExecutionIdRoute
  '/w/$slug/settings/members': typeof WSlugSettingsMembersRoute
  '/w/$slug/settings/secrets': typeof WSlugSettingsSecretsRoute
  '/w/$slug/workflows/$workflowId': typeof WSlugWorkflowsWorkflowIdRouteWithChildren
  '/w/$slug/executions/': typeof WSlugExecutionsIndexRoute
  '/w/$slug/settings/': typeof WSlugSettingsIndexRoute
  '/w/$slug/workflows/': typeof WSlugWorkflowsIndexRoute
  '/w/$slug/workflows/$workflowId/builder': typeof WSlugWorkflowsWorkflowIdBuilderRoute
  '/w/$slug/workflows/$workflowId/': typeof WSlugWorkflowsWorkflowIdIndexRoute
  '/w/$slug/workflows/$workflowId/executions/$executionId': typeof WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/w/$slug/approvals': typeof WSlugApprovalsRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/executions/$executionId': typeof WSlugExecutionsExecutionIdRoute
  '/w/$slug/settings/members': typeof WSlugSettingsMembersRoute
  '/w/$slug/settings/secrets': typeof WSlugSettingsSecretsRoute
  '/w/$slug/executions': typeof WSlugExecutionsIndexRoute
  '/w/$slug/settings': typeof WSlugSettingsIndexRoute
  '/w/$slug/workflows': typeof WSlugWorkflowsIndexRoute
  '/w/$slug/workflows/$workflowId/builder': typeof WSlugWorkflowsWorkflowIdBuilderRoute
  '/w/$slug/workflows/$workflowId': typeof WSlugWorkflowsWorkflowIdIndexRoute
  '/w/$slug/workflows/$workflowId/executions/$executionId': typeof WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/approvals': typeof WSlugApprovalsRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/executions/$executionId': typeof WSlugExecutionsExecutionIdRoute
  '/w/$slug/settings/members': typeof WSlugSettingsMembersRoute
  '/w/$slug/settings/secrets': typeof WSlugSettingsSecretsRoute
  '/w/$slug/workflows/$workflowId': typeof WSlugWorkflowsWorkflowIdRouteWithChildren
  '/w/$slug/executions/': typeof WSlugExecutionsIndexRoute
  '/w/$slug/settings/': typeof WSlugSettingsIndexRoute
  '/w/$slug/workflows/': typeof WSlugWorkflowsIndexRoute
  '/w/$slug/workflows/$workflowId/builder': typeof WSlugWorkflowsWorkflowIdBuilderRoute
  '/w/$slug/workflows/$workflowId/': typeof WSlugWorkflowsWorkflowIdIndexRoute
  '/w/$slug/workflows/$workflowId/executions/$executionId': typeof WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/workspaces'
    | '/accept-invitation/$invitationId'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/w/$slug'
    | '/w/$slug/approvals'
    | '/w/$slug/notifications'
    | '/w/$slug/'
    | '/w/$slug/executions/$executionId'
    | '/w/$slug/settings/members'
    | '/w/$slug/settings/secrets'
    | '/w/$slug/workflows/$workflowId'
    | '/w/$slug/executions/'
    | '/w/$slug/settings/'
    | '/w/$slug/workflows/'
    | '/w/$slug/workflows/$workflowId/builder'
    | '/w/$slug/workflows/$workflowId/'
    | '/w/$slug/workflows/$workflowId/executions/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/workspaces'
    | '/accept-invitation/$invitationId'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/w/$slug/approvals'
    | '/w/$slug/notifications'
    | '/w/$slug'
    | '/w/$slug/executions/$executionId'
    | '/w/$slug/settings/members'
    | '/w/$slug/settings/secrets'
    | '/w/$slug/executions'
    | '/w/$slug/settings'
    | '/w/$slug/workflows'
    | '/w/$slug/workflows/$workflowId/builder'
    | '/w/$slug/workflows/$workflowId'
    | '/w/$slug/workflows/$workflowId/executions/$executionId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/workspaces'
    | '/accept-invitation/$invitationId'
    | '/onboarding/invite'
    | '/onboarding/workspace'
    | '/w/$slug'
    | '/w/$slug/approvals'
    | '/w/$slug/notifications'
    | '/w/$slug/'
    | '/w/$slug/executions/$executionId'
    | '/w/$slug/settings/members'
    | '/w/$slug/settings/secrets'
    | '/w/$slug/workflows/$workflowId'
    | '/w/$slug/executions/'
    | '/w/$slug/settings/'
    | '/w/$slug/workflows/'
    | '/w/$slug/workflows/$workflowId/builder'
    | '/w/$slug/workflows/$workflowId/'
    | '/w/$slug/workflows/$workflowId/executions/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
  WSlugRoute: typeof WSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/onboarding/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/onboarding/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/notifications': {
      id: '/w/$slug/notifications'
      path: '/notifications'
      fullPath: '/w/$slug/notifications'
      preLoaderRoute: typeof WSlugNotificationsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/approvals': {
      id: '/w/$slug/approvals'
      path: '/approvals'
      fullPath: '/w/$slug/approvals'
      preLoaderRoute: typeof WSlugApprovalsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/workflows/': {
      id: '/w/$slug/workflows/'
      path: '/workflows'
      fullPath: '/w/$slug/workflows/'
      preLoaderRoute: typeof WSlugWorkflowsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings/': {
      id: '/w/$slug/settings/'
      path: '/settings'
      fullPath: '/w/$slug/settings/'
      preLoaderRoute: typeof WSlugSettingsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/executions/': {
      id: '/w/$slug/executions/'
      path: '/executions'
      fullPath: '/w/$slug/executions/'
      preLoaderRoute: typeof WSlugExecutionsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/workflows/$workflowId': {
      id: '/w/$slug/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/w/$slug/workflows/$workflowId'
      preLoaderRoute: typeof WSlugWorkflowsWorkflowIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings/secrets': {
      id: '/w/$slug/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/w/$slug/settings/secrets'
      preLoaderRoute: typeof WSlugSettingsSecretsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings/members': {
      id: '/w/$slug/settings/members'
      path: '/settings/members'
      fullPath: '/w/$slug/settings/members'
      preLoaderRoute: typeof WSlugSettingsMembersRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/executions/$executionId': {
      id: '/w/$slug/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/w/$slug/executions/$executionId'
      preLoaderRoute: typeof WSlugExecutionsExecutionIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/workflows/$workflowId/': {
      id: '/w/$slug/workflows/$workflowId/'
      path: '/'
      fullPath: '/w/$slug/workflows/$workflowId/'
      preLoaderRoute: typeof WSlugWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof WSlugWorkflowsWorkflowIdRoute
    }
    '/w/$slug/workflows/$workflowId/builder': {
      id: '/w/$slug/workflows/$workflowId/builder'
      path: '/builder'
      fullPath: '/w/$slug/workflows/$workflowId/builder'
      preLoaderRoute: typeof WSlugWorkflowsWorkflowIdBuilderRouteImport
      parentRoute: typeof WSlugWorkflowsWorkflowIdRoute
    }
    '/w/$slug/workflows/$workflowId/executions/$executionId': {
      id: '/w/$slug/workflows/$workflowId/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/w/$slug/workflows/$workflowId/executions/$executionId'
      preLoaderRoute: typeof WSlugWorkflowsWorkflowIdExecutionsExecutionIdRouteImport
      parentRoute: typeof WSlugWorkflowsWorkflowIdRoute
    }
  }
}

interface WSlugWorkflowsWorkflowIdRouteChildren {
  WSlugWorkflowsWorkflowIdBuilderRoute: typeof WSlugWorkflowsWorkflowIdBuilderRoute
  WSlugWorkflowsWorkflowIdIndexRoute: typeof WSlugWorkflowsWorkflowIdIndexRoute
  WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute: typeof WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute
}

const WSlugWorkflowsWorkflowIdRouteChildren: WSlugWorkflowsWorkflowIdRouteChildren =
  {
    WSlugWorkflowsWorkflowIdBuilderRoute: WSlugWorkflowsWorkflowIdBuilderRoute,
    WSlugWorkflowsWorkflowIdIndexRoute: WSlugWorkflowsWorkflowIdIndexRoute,
    WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute:
      WSlugWorkflowsWorkflowIdExecutionsExecutionIdRoute,
  }

const WSlugWorkflowsWorkflowIdRouteWithChildren =
  WSlugWorkflowsWorkflowIdRoute._addFileChildren(
    WSlugWorkflowsWorkflowIdRouteChildren,
  )

interface WSlugRouteChildren {
  WSlugApprovalsRoute: typeof WSlugApprovalsRoute
  WSlugNotificationsRoute: typeof WSlugNotificationsRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
  WSlugExecutionsExecutionIdRoute: typeof WSlugExecutionsExecutionIdRoute
  WSlugSettingsMembersRoute: typeof WSlugSettingsMembersRoute
  WSlugSettingsSecretsRoute: typeof WSlugSettingsSecretsRoute
  WSlugWorkflowsWorkflowIdRoute: typeof WSlugWorkflowsWorkflowIdRouteWithChildren
  WSlugExecutionsIndexRoute: typeof WSlugExecutionsIndexRoute
  WSlugSettingsIndexRoute: typeof WSlugSettingsIndexRoute
  WSlugWorkflowsIndexRoute: typeof WSlugWorkflowsIndexRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugApprovalsRoute: WSlugApprovalsRoute,
  WSlugNotificationsRoute: WSlugNotificationsRoute,
  WSlugIndexRoute: WSlugIndexRoute,
  WSlugExecutionsExecutionIdRoute: WSlugExecutionsExecutionIdRoute,
  WSlugSettingsMembersRoute: WSlugSettingsMembersRoute,
  WSlugSettingsSecretsRoute: WSlugSettingsSecretsRoute,
  WSlugWorkflowsWorkflowIdRoute: WSlugWorkflowsWorkflowIdRouteWithChildren,
  WSlugExecutionsIndexRoute: WSlugExecutionsIndexRoute,
  WSlugSettingsIndexRoute: WSlugSettingsIndexRoute,
  WSlugWorkflowsIndexRoute: WSlugWorkflowsIndexRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WorkspacesRoute: WorkspacesRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
  WSlugRoute: WSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
